//
//  SkipUITests.swift
//  NavigationExampleUITests
//
//  Created by Sergey Balalaev on 13.10.2023.
//

import XCTest

final class SkipUITests: XCTestCase {

    override func setUpWithError() throws {
        continueAfterFailure = false
    }

    override func tearDownWithError() throws {
    }

    func testSimple() throws {
        let app = XCUIApplication.launchEn
        MainView(app: app)
            .checkThis()
            .checkChanging(false)
            .tapSecond()
        SecondView(app: app)
            .checkThis(number: 11)
            .tapBool()
        BoolView(app: app)
            .checkThis()
            .enterSkipTextField("Second")
            .tapSkip()
            .tapDismiss()
        MainView(app: app)
            .checkThis()
            .checkRootMessage(tapOK: true)
    }

    // Not stable on iOS 17.2
    func testDoubleSkipAfterRepeat() throws {
        let app = XCUIApplication.launchEn
        MainView(app: app)
            .checkThis()
            .checkChanging(false)
            .tapFirst()
        FirstView(app: app)
            .checkThis(string: "Hi")
            .tapSecond22()
        SecondView(app: app)
            .checkThis(number: 22)
            .tapBool()
        BoolView(app: app)
            .checkThis()
            .enterSkipTextField("Second")
            .tapSkip()
            .tapBack()
        FirstView(app: app)
            .checkThis(string: "Hi")
            .tapSecond22()
        SecondView(app: app)
            .checkThis(number: 22)
            .tapBool()
        BoolView(app: app)
            .checkThis()
            .tapChange()
            .enterSkipTextField("First")
            .tapSkip()
            .tapClearSkip()
            .enterSkipTextField("Second")
            .tapSkip()
            .swipeBack()
        MainView(app: app)
            .checkThis()
    }

    func testSkipToRoot() throws {
        let app = XCUIApplication.launchEn
        MainView(app: app)
            .checkThis()
            .checkChanging(false)
            .tapFirst()
        FirstView(app: app)
            .checkThis(string: "Hi")
            .tapSecond22()
        SecondView(app: app)
            .checkThis(number: 22)
            .tapBool()
        BoolView(app: app)
            .checkThis()
            .enterSkipTextField("First")
            .tapSkip()
            .tapClearSkip()
            .enterSkipTextField("Second")
            .tapSkip()
            .tapDismiss()
        MainView(app: app)
            .checkThis()
            .checkRootMessage(tapOK: true)
    }

    func testNotFound() throws {
        let app = XCUIApplication.launchEn
        MainView(app: app)
            .checkThis()
            .checkChanging(false)
            .tapSecond()
        SecondView(app: app)
            .checkThis(number: 11)
            .tapBool()
        BoolView(app: app)
            .checkThis()
            .enterSkipTextField("First")
            .tapSkip()
            .checkThis()
            .tapBack()
        SecondView(app: app)
            .checkThis(number: 11)
            .tapBack()
        MainView(app: app)
            .checkThis()
            .checkRootMessage(tapOK: true)
    }

    func testPopToTheSame() throws {
        let app = XCUIApplication.launchEn
        MainView(app: app)
            .checkThis()
            .checkChanging(false)
            .tapSecond()
        SecondView(app: app)
            .checkThis(number: 11)
            .tapBool()
        BoolView(app: app)
            .checkThis()
            .enterSkipTextField("Bool")
            .tapSkip()
            .checkThis()
            .tapBack()
        SecondView(app: app)
            .checkThis(number: 11)
            .tapBack()
        MainView(app: app)
            .checkThis()
            .checkRootMessage(tapOK: true)
    }

    /// It's not bug, a feature. When stack has the same id, we can not skip it.
    func testSkipTheSameWithDouble() throws {
        let app = XCUIApplication.launchEn
        MainView(app: app)
            .checkThis()
            .checkChanging(false)
            .tapBool()
        BoolView(app: app)
            .checkThis()
            .tapFirst()
        FirstView(app: app)
            .checkThis(string: "Bool")
            .tapSecond22()
        SecondView(app: app)
            .checkThis(number: 22)
            .tapBool()
        BoolView(app: app)
            .checkThis()
            .enterSkipTextField("Bool")
            .tapSkip()
        BoolView(app: app)
            .checkThis()
            .tapBack()
        SecondView(app: app)
            .checkThis(number: 22)
            .tapBack()
        FirstView(app: app)
            .checkThis(string: "Bool")
            .tapBack()
        BoolView(app: app)
            .checkThis()
            .tapBack()
        MainView(app: app)
            .checkThis()
            .checkRootMessage(tapOK: true)
    }

    func testSkipManyClones() throws {
        let app = XCUIApplication.launchEn
        MainView(app: app)
            .checkThis()
            .checkChanging(false)
            .tapFirst()
        FirstView(app: app)
            .checkThis(string: "Hi")
            .tapSecond22()
        SecondView(app: app)
            .checkThis(number: 22)
            .tapBool()
        BoolView(app: app)
            .checkThis()
            .tapFirst()
        FirstView(app: app)
            .checkThis(string: "Bool")
            .tapSecond22()
        SecondView(app: app)
            .checkThis(number: 22)
            .tapBool()
        BoolView(app: app)
            .checkThis()
            .tapChange()
            .enterSkipTextField("First")
            .tapSkip()
            .tapBack()
        SecondView(app: app)
            .checkThis(number: 22)
            .tapBack()
        BoolView(app: app)
            .checkThis()
            .enterSkipTextField("Second")
            .tapSkip()
            .tapDismiss()
        FirstView(app: app)
            .checkThis(string: "Hi")
            .tapBack()
        MainView(app: app)
            .checkThis()
    }

    // Not stable on iOS 16.4
    func testRepeat() throws {
        let app = XCUIApplication.launchEn
        MainView(app: app)
            .checkThis()
            .checkChanging(false)
            .tapFirst()
        FirstView(app: app)
            .checkThis(string: "Hi")
            .tapSecond22()
        SecondView(app: app)
            .checkThis(number: 22)
            .tapBool()
        BoolView(app: app)
            .checkThis()
            .tapChange()
            .enterSkipTextField("First")
            .tapSkip()
            .tapClearSkip()
            .enterSkipTextField("Second")
            .tapSkip()
            .swipeBack()
        MainView(app: app)
            .checkThis()
            .tapFirst()
        FirstView(app: app)
            .checkThis(string: "Hi")
            .tapSecond22()
        SecondView(app: app)
            .checkThis(number: 22)
            .tapBool()
        BoolView(app: app)
            .checkThis()
            .tapChange()
            .enterSkipTextField("First")
            .tapSkip()
            .tapClearSkip()
            .enterSkipTextField("Second")
            .tapSkip()
            .tapBack()
        MainView(app: app)
            .checkThis()
            .checkRootMessage(tapOK: true)
            .tapFirst()
        FirstView(app: app)
            .checkThis(string: "Hi")
            .tapSecond22()
        SecondView(app: app)
            .checkThis(number: 22)
            .tapBool()
        BoolView(app: app)
            .checkThis()
            .tapChange()
            .enterSkipTextField("First")
            .tapSkip()
            .tapClearSkip()
            .enterSkipTextField("Second")
            .tapSkip()
            .tapDismiss()
        MainView(app: app)
            .checkThis()
            .tapFirst()
        FirstView(app: app)
            .checkThis(string: "Hi")
            .tapSecond22()
        SecondView(app: app)
            .checkThis(number: 22)
            .tapBool()
        BoolView(app: app)
            .checkThis()
            .tapChange()
            .enterSkipTextField("First")
            .tapSkip()
            .tapClearSkip()
            .enterSkipTextField("Second")
            .tapSkip()
            .tapPopTo()
        MainView(app: app)
            .checkThis()
            .checkRootMessage(tapOK: true)
            .tapFirst()
        FirstView(app: app)
            .checkThis(string: "Hi")
            .tapSecond22()
        SecondView(app: app)
            .checkThis(number: 22)
            .tapBool()
        BoolView(app: app)
            .checkThis()
            .tapChange()
            .enterSkipTextField("First")
            .tapSkip()
            .tapClearSkip()
            .enterSkipTextField("Second")
            .tapSkip()
            .tapRoot()
        MainView(app: app)
            .checkThis()
    }
}
